---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/24 15:51
---
local val = redis.call('get', KEYS[1])
if val == ARGV[1] then
    return redis.call('expire', KEYS[1], ARGV[2])
else
    return 0
end